os: linux
arch:
  - arm64
  - ppc64le
  - s390x

language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'

install:
  - pip install setuptools==60.8.2
  - pip install -r requirements.txt
  - pip install .

script: pytest
